# Generated by Django 6.1.1 on 2026-10-05 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogador', models.CharField(max_length=10)),
                ('computador', models.CharField(max_length=10)),
                ('resultado', models.CharField(max_length=10)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
